### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by tomasweigenast** [PavieOlivier/AndroidNotificationListener#2] opened 2020-07-16 12:28 UTC
Hi, I got a crash when I try to run an app. The first open is run perfectly, it opens the setting to allow the app to access notifications, but when I give permission, it crashes with this exception: 

```
D/AndroidRuntime(20543): Shutting down VM
E/AndroidRuntime(20543): FATAL EXCEPTION: main
E/AndroidRuntime(20543): Process: com.example.notification_tracker, PID: 20543
E/AndroidRuntime(20543): java.lang.RuntimeException: Unable to create service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.InstantiationException: java.lang.Class<com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin> has no zero argument constructor
E/AndroidRuntime(20543): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4103)
E/AndroidRuntime(20543): 	at android.app.ActivityThread.access$1500(ActivityThread.java:233)
E/AndroidRuntime(20543): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1915)
E/AndroidRuntime(20543): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20543): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(20543): 	at android.app.ActivityThread.main(ActivityThread.java:7523)
E/AndroidRuntime(20543): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20543): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(20543): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/AndroidRuntime(20543): Caused by: java.lang.InstantiationException: java.lang.Class<com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin> has no zero argument constructor
E/AndroidRuntime(20543): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(20543): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(20543): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
E/AndroidRuntime(20543): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4082)
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54644/bCZhNP0Lvok=/ws
D/AndroidRuntime(20543): Shutting down VM
E/AndroidRuntime(20543): FATAL EXCEPTION: main
E/AndroidRuntime(20543): Process: com.example.notification_tracker, PID: 20543
E/AndroidRuntime(20543): 	... 8 more
I/Process (20543): Sending signal. PID: 20543 SIG: 9

```

Tested with an Android emulator. Pixel 3A API 30 x86. Android 10.0+ (Google APIs)

**Comment by nightMue** [comment] 2020-07-18 02:11
I am getting the same result with crashing after giving the app permission. Then all other launches of the app it crashes.

**Comment by sharecube** [comment] 2020-07-30 03:08
confirm, the same

**Comment by PavieOlivier** [comment] 2020-08-19 07:06
Hello, Sorry for the delay, are you referring to the example application?
If yes, please do not use it, just refer to the code.

- Create a new project,
- add the package to the YAML file
- follow the setup process as explained in the description
- come here and copy the content of the main.dart file
- paste that content inside your new main.dart file
- Run the application 

This will mostly work 95% of the time.
**The plugin itself is working fine** but the example folder has some issues that I am not able to resolve because of a huge lack of time (currently working on an important project ).

Please if you try the above solution and it does not work let me know and I will make some time to look into this matter seriously, but if the scope of the issue is only limited to the example folder, then it will have to wait until I finish with the work I am currently doing

**Comment by PavieOlivier** [comment] 2020-08-20 12:26
Hello everyone, I just pushed an overall upgrade (**on this repo only**) and changed almost all the files.
This should work now, can you please try to fork and run the example code from here

**Comment by PavieOlivier** [comment] 2020-08-20 13:58
I am closing this issue since another person (on another same issue) said that the problem is fixed, I published another version of this package at pub.dev

- https://pub.dev/packages/android_notification_listener2

If you still have an issue, feel free to re-open or comment here

**Closed as completed by PavieOlivier** 2020-08-20 13:58 UTC
Labels: solved
