### ISSUE TITLE
Example app crash

### ISSUE THREAD

**Issue by stonega** [PavieOlivier/AndroidNotificationListener#1] opened 2020-06-04 14:50 UTC
Hi, 
Thanks for the plugin. truly what I want. I try to run example on my phone, at first the app launch, ask for notification permission, I tap allow, then the app crash.

```
Connecting to VM Service at ws://127.0.0.1:5652/D6V-FH7fKj0=/ws
D/AndroidRuntime(23078): Shutting down VM
E/AndroidRuntime(23078): FATAL EXCEPTION: main
E/AndroidRuntime(23078): Process: com.emilecode.android_notification_listener_example, PID: 23078
E/AndroidRuntime(23078): java.lang.RuntimeException: Unable to instantiate service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.InstantiationException: java.lang.Class<com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin> has no zero argument constructor
E/AndroidRuntime(23078): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3940)
E/AndroidRuntime(23078): 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
E/AndroidRuntime(23078): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
E/AndroidRuntime(23078): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(23078): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(23078): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(23078): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23078): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(23078): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(23078): Caused by: java.lang.InstantiationException: java.lang.Class<com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin> has no zero argument constructor
E/AndroidRuntime(23078): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(23078): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(23078): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
E/AndroidRuntime(23078): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3935)
E/AndroidRuntime(23078): 	... 8 more
I/Process (23078): Sending signal. PID: 23078 SIG: 9
Lost connection to device.
```

**Comment by PavieOlivier** [comment] 2020-06-04 15:02
Allo, Hum This is the 1st time I see this error on my plugin... 
What is the Android version of the phone you are attempting the installation, did you try with a different phone? what about the emulator?

**Comment by PavieOlivier** [comment] 2020-06-04 15:02
I cannot look into it today, I will try and have a look tomorrow and I will be back

**Comment by stonega** [comment] 2020-06-04 15:20
Thanks for reply, I am using Android 10 on Pixel 3 XL. I will have more test and reply you later.

**Comment by dxganta** [comment] 2020-06-20 16:46
I am getting the same error too

**Comment by abdoubarah** [comment] 2020-06-23 14:26
getting the same error too

**Comment by PavieOlivier** [comment] 2020-06-23 14:31
Hello Give me 10 min i will take a closer look into it: (I have been busy with a client so the time to maintain this asset reduced. I am sorry for the delay)

However, I am confident that the actual plugin is performing well... let's see what is going on there

**Comment by PavieOlivier** [comment] 2020-06-23 14:58
I am not getting this error on my laptop.
@stonega tell me, does the original plugin work for you?
I made some change on the pubspec to point directly to the hosted repository

**Comment by stonega** [comment] 2020-06-23 15:16
@PavieOlivier I just clone the recent version, and try to run example on my phone, still the same error. 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18363.900], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)
[√] Connected device (3 available) Android 10 Pixel3XL
```

**Comment by stonega** [comment] 2020-06-23 15:21
@PavieOlivier  I am a little confused, what do you mean original plugin? How to test it? 
I am very glad to help to investigate the issue.

**Comment by PavieOlivier** [comment] 2020-06-23 16:02
> @PavieOlivier I am a little confused, what do you mean original plugin? How to test it?
> I am very glad to help to investigate the issue.


Actually, here is the issue 
Now, since I have a user-defined constructor, the compiler does not provide me with any default constructors, so I need to define a parameterless constructor myself too. by doing this
```
public ClassName()
{
    //code here
}
```
When I make that change though.. my build crash.... so I am looking into it
However, I thought that it was not necessary so i did not put it inside the code since it was working perfectly inside the phones I used. This is what is confusing me.
so what I was asking you is 
1) did you try creating a blanc project,
2) copying the code in the main file (of this example) and pasting it inside your blanc project, then adding the package name on your pubspec file 
3) adding the necessary line on the AndroidManifest and running the app for yourself?

**Comment by PavieOlivier** [comment] 2020-06-23 16:11
@stonega, @abdoubarah , @realdiganta   please fork the entire project please and try again, I made some change to the main class. does the crash still happen?
If not I will submit a new version of this plugin on pub.dev

**Comment by stonega** [comment] 2020-06-23 16:36
I forked and run example again. Error log changed, but still crashed.
```
D/AndroidRuntime(14920): Shutting down VM
E/AndroidRuntime(14920): FATAL EXCEPTION: main
E/AndroidRuntime(14920): Process: com.emilecode.android_notification_listener_example, PID: 14920
E/AndroidRuntime(14920): java.lang.RuntimeException: Unable to create service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(14920): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4103)
E/AndroidRuntime(14920): 	at android.app.ActivityThread.access$1500(ActivityThread.java:233)
E/AndroidRuntime(14920): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1915)
E/AndroidRuntime(14920): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14920): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14920): 	at android.app.ActivityThread.main(ActivityThread.java:7523)
E/AndroidRuntime(14920): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14920): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14920): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/AndroidRuntime(14920): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(14920): 	at com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin.permissionGiven(AndroidNotificationListenerPlugin.java:118)
E/AndroidRuntime(14920): 	at com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin.<init>(AndroidNotificationListenerPlugin.java:54)
E/AndroidRuntime(14920): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(14920): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(14920): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
E/AndroidRuntime(14920): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4082)
E/AndroidRuntime(14920): 	... 8 more
I/Process (14920): Sending signal. PID: 14920 SIG: 9
Lost connection to device.
```

**Comment by abdoubarah** [comment] 2020-06-23 17:20
I still got the same probleme 

D/AndroidRuntime(19922): Shutting down VM
E/AndroidRuntime(19922): FATAL EXCEPTION: main
E/AndroidRuntime(19922): Process: com.emilecode.android_notification_listener_example, PID: 19922
E/AndroidRuntime(19922): java.lang.RuntimeException: Unable to instantiate service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(19922): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3545)
E/AndroidRuntime(19922): 	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
E/AndroidRuntime(19922): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
E/AndroidRuntime(19922): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19922): 	at android.os.Looper.loop(Looper.java:198)
E/AndroidRuntime(19922): 	at android.app.ActivityThread.main(ActivityThread.java:6732)
E/AndroidRuntime(19922): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19922): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(19922): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(19922): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(19922): 	at com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin.permissionGiven(AndroidNotificationListenerPlugin.java:109)
E/AndroidRuntime(19922): 	at com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin.<init>(AndroidNotificationListenerPlugin.java:50)

**Comment by clezioalves** [comment] 2020-06-30 09:43
I got the same problem:

`E/AndroidRuntime( 8153): java.lang.RuntimeException: Unable to instantiate service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.InstantiationException: java.lang.Class<com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin> has no zero argument constructor
E/AndroidRuntime( 8153): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3974)
E/AndroidRuntime( 8153): 	at android.app.ActivityThread.access$1600(ActivityThread.java:220)
E/AndroidRuntime( 8153): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1899)
E/AndroidRuntime( 8153): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 8153): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime( 8153): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/AndroidRuntime( 8153): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8153): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime( 8153): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime( 8153): Caused by: java.lang.InstantiationException: java.lang.Class<com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin> has no zero argument constructor
E/AndroidRuntime( 8153): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime( 8153): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime( 8153): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
E/AndroidRuntime( 8153): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3969)
E/AndroidRuntime( 8153): 	... 8 more`

**Comment by WesleyBatista** [comment] 2020-07-04 21:46
I just forked and cloned the project. Getting the same error as the fellows above (`origin/master` is fe5df5c)

![](https://user-images.githubusercontent.com/755254/86521348-d694ef00-be4f-11ea-98cf-4d635d4a544c.png)

using vscode, running **Debub** provided by the flutter plugin:

![](https://user-images.githubusercontent.com/755254/86521381-620e8000-be50-11ea-9fad-25dc70561136.png)

**Comment by WesleyBatista** [comment] 2020-07-04 22:19
I am observing that the current plugin initialization is not respecting the v2 API. could that be the reason? :thinking:

compare:

https://github.com/PavieOlivier/AndroidNotificationListener/blob/fe5df5c8f933d4650f21bb7f2340edec62b32f9f/android/src/main/java/com/emilecode/android_notification_listener/AndroidNotificationListenerPlugin.java#L29-L63

![](https://user-images.githubusercontent.com/755254/86521755-190cfa80-be55-11ea-97d7-5573f8ad3d56.png)

Ref.: https://medium.com/flutter/modern-flutter-plugin-development-4c3ee015cf5a

**Comment by djprawns** [comment] 2020-07-09 20:41
Crashes for me too however I get a `null object reference error` as follows : - 

```Launching lib/main.dart on Pixel 2 XL in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Debug service listening on ws://127.0.0.1:62865/RCtKN7NiJQM=/ws
Syncing files to device Pixel 2 XL...
D/AndroidRuntime(13223): Shutting down VM
E/AndroidRuntime(13223): FATAL EXCEPTION: main
E/AndroidRuntime(13223): Process: com.emilecode.android_notification_listener_example, PID: 13223
E/AndroidRuntime(13223): java.lang.RuntimeException: Unable to instantiate service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(13223): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3940)
E/AndroidRuntime(13223): 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
E/AndroidRuntime(13223): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
E/AndroidRuntime(13223): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(13223): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(13223): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(13223): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13223): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(13223): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(13223): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(13223): 	at com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin.permissionGiven(AndroidNotificationListenerPlugin.java:109)
E/AndroidRuntime(13223): 	at com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin.<init>(AndroidNotificationListenerPlugin.java:50)
E/AndroidRuntime(13223): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(13223): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(13223): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
E/AndroidRuntime(13223): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3935)
E/AndroidRuntime(13223): 	... 8 more
I/Process (13223): Sending signal. PID: 13223 SIG: 9
Lost connection to device.
```

**Comment by PavieOlivier** [comment] 2020-08-19 07:17
Hello, very very sorry for the delay, as you are all referring to the actual example application
I would like to ask you not to use is (as is ! ), just refer to the code and write it out yourself.
As I mentioned here

> However, I am confident that the actual plugin is performing well... let's see what is going on there

The actual plugin is working fine, but the example folder is the one causing trouble.
Please follow these instructions  

- Create a new Flutter project,
- add the package to the YAML file
- follow the setup process as explained in the description of the plugin
- come here and **copy the content** of the main.dart file
- paste that content inside your new main.dart file
- Run the application 

This will mostly work 95% of the time.
**The plugin itself is working fine** but the example folder has some issues that I am not able to resolve because of a huge lack of time (currently working on an important project ).

**Please if you try the above solution and it does not work let me know and I will make some time to look into this matter much more seriously, but if the scope of the issue is only limited to the example folder, then it will have to wait until I finish with the work I am currently doing** 

And once again I really apologize for the delay. I know it is frustrating especially when you have an important coding work going on and finding an alternative can be a pain. 

thank you

**Comment by clezioalves** [comment] 2020-08-20 09:49
Not working for me, @PavieOlivier.

**Comment by PavieOlivier** [comment] 2020-08-20 09:51
ok, give me 2 to 3 hours I will just recreate the plugin from scratch using kotlin

**Comment by PavieOlivier** [comment] 2020-08-20 12:25
Hello everyone, I just pushed an overall upgrade (**on this repo only**) and changed almost all the files.
This should work now, can you please try to fork and run the example code from here.
Once anyone confirms it is working for them, I will push it to pub.dev

**Comment by PavieOlivier** [comment] 2020-08-20 13:57
I am closing this issue since another person (on another same issue) said that the problem is fixed, I published another version of this package at pub.dev

- https://pub.dev/packages/android_notification_listener2

If you still have an issue, feel free to re-open or comment here

**Closed as completed** 2020-08-20 13:58 UTC
Labels: solved
